server:
    port: 8081

spring:
    cloud:
      gateway:
         routes:
         - id: disease-module
           uri: http://localhost:8082/
           predicates:
              - Path=/diseases
         - id: doctors-module
           uri: http://localhost:8083/
           predicates:
              - Path=/doctors
         - id: patients-module
           uri: http://localhost:8084/
           predicates:
              - Path=/patients